#!/bin/bash
alias grub-update='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias python='python2'
alias ls='ls -F --color --quoting-style=escape'
alias cal='ncal -Mwb -B1 -A1'
alias tags='ctags -R -f ./tags'

function com {
	local com_log=/tmp/picocom.log

	if [ -z $1 ]; then
		sudo picocom -b 115200 -e b /dev/ttyUSB0 | tee $com_log
	else
		sudo picocom -b 115200 -e b "$@" | tee $com_log
	fi

}

function pilog() {
	if [ -z $1 ]; then
		tail -n +0  -f /tmp/picocom.log
	else
		tail -n +0  -f /tmp/picocom.log | grep --binary-file=text $@
	fi
}

function rbg() {
	if [ -z $1 ]; then
		echo "ERROR: No arguments supplied!"
		echo "Usage: rbg <command> <args>"
		return 1
	fi

	echo "Logs in /tmp/rbg.log"
	eval "$@" 2>&1 > /tmp/rbg.log &
	disown %2
}


function obg() {
	if [ -z $1 ]; then
		echo "ERROR: No arguments supplied!"
		echo "Usage: obg <command> <args>"
		return 1
	fi

	echo "Logs in /tmp/obg.log"
	eval xdg-open "$@" 2>&1 > /tmp/obg.log &
	disown %2
}


