#!/bin/bash
alias grub-update='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias python='python2'
alias emc='emc -nw'
alias ls='ls -F --color'
alias cal='ncal -Mwb -B1 -A1'
alias pu="pushd . > /dev/null"
alias po='popd >/dev/null'
alias tig='git log --graph --oneline --decorate'
