#!/bin/bash
export $(dbus-launch)
export TERM=xterm-256color
export WINEPREFIX=~/.wine
export WINEARCH=win32
export EDITOR='emacsclient -t'
export DIFFPROG='meld'
export PATH=$PATH:/home/sejo/.gem/ruby/2.2.0/bin 
export SWT_GTK3=1

#LS settings
export LS_COLORS_THEMES_ROOTDIR=~/.dircolors
export LS_COLORS_THEME=$LS_COLORS_THEMES_ROOTDIR/dircolors.ansi-dark

if [ -f $LS_COLORS_THEME ];
then
    eval `dircolors $LS_COLORS_THEME`
fi

# LESS settings
export LESS=-R
unset LESSCHARSET
export LESS_TERMCAP_mb=$(printf "\e[1;31m")
export LESS_TERMCAP_md=$(printf "\e[1;31m")
export LESS_TERMCAP_me=$(printf "\e[0m")
export LESS_TERMCAP_se=$(printf "\e[0m")
export LESS_TERMCAP_so=$(printf "\e[0;37;102m")
export LESS_TERMCAP_ue=$(printf "\e[0m")
export LESS_TERMCAP_us=$(printf "\e[4;32m")


